---
- name: Monitor CPU Utilization
  hosts: 192.168.116.10
  sources:
    - ansible.eda.sources.monitoring:
        type: cpu
        threshold: 60

  rules:
    - name: Check CPU Usage
      condition: event.utilization > 60
      action:
        run_job_template:
          name: monitoring_threshold
          organization: Default
